Fix `InferenceTableSpanProcessor` init for opentelemetry-sdk 1.41.0
This takes the change to:

  mlflow/tracing/processor/inference_table.py

From commit:

  dc391d3b6f66ff30e95805b1d7af3fdb470fa659

See https://github.com/mlflow/mlflow/pull/22867

Without this the upgraded opentelemetry-sdk version results in the
following error:

  AttributeError: 'InferenceTableSpanProcessor' object has no attribute '_metrics'

Signed-off-by: Jon Burdo <jon@jonburdo.com>